on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 1/10 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'nginxinc/docker-nginx'
        path: docker-nginx
    - run: podman build --build-arg ENABLED_MODULES="brotli" -t lizkes/nginx-brotli:latest -f Dockerfile .
      working-directory: docker-nginx/modules
    - run: podman build --build-arg ENABLED_MODULES="brotli" -t lizkes/nginx-brotli:alpine -f Dockerfile.alpine .
      working-directory: docker-nginx/modules
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: |
        NGINX_VERSION=$(podman run --rm lizkes/nginx-brotli:latest bash -c "echo \$NGINX_VERSION")
        echo $NGINX_VERSION
        NGINX_VERSION_MAJMIN=$(printf '%s' "$NGINX_VERSION" | sed -r 's/([0-9]+)\.([0-9]+)\.([0-9]+)/\1.\2/g')
        echo $NGINX_VERSION_MAJMIN
        NGINX_VERSION_MAJ=$(printf '%s' "$NGINX_VERSION" | sed -r 's/([0-9]+)\.([0-9]+)\.([0-9]+)/\1/g')
        echo $NGINX_VERSION_MAJ
        podman tag lizkes/nginx-brotli:latest lizkes/nginx-brotli:$NGINX_VERSION
        podman tag lizkes/nginx-brotli:latest lizkes/nginx-brotli:$NGINX_VERSION_MAJMIN
        podman tag lizkes/nginx-brotli:latest lizkes/nginx-brotli:$NGINX_VERSION_MAJ
        podman tag lizkes/nginx-brotli:alpine lizkes/nginx-brotli:$NGINX_VERSION-alpine
        podman tag lizkes/nginx-brotli:alpine lizkes/nginx-brotli:$NGINX_VERSION_MAJMIN-alpine
        podman tag lizkes/nginx-brotli:alpine lizkes/nginx-brotli:$NGINX_VERSION_MAJ-alpine
        podman push lizkes/nginx-brotli:latest
        podman push lizkes/nginx-brotli:$NGINX_VERSION
        podman push lizkes/nginx-brotli:$NGINX_VERSION_MAJMIN
        podman push lizkes/nginx-brotli:$NGINX_VERSION_MAJ
        podman push lizkes/nginx-brotli:alpine
        podman push lizkes/nginx-brotli:$NGINX_VERSION-alpine
        podman push lizkes/nginx-brotli:$NGINX_VERSION_MAJMIN-alpine
        podman push lizkes/nginx-brotli:$NGINX_VERSION_MAJ-alpine
